### ISSUE TITLE
Would the maintainers and contributors forgive me?

### ISSUE THREAD

**Issue by asl97** [Nullspeaker/ch.py#62]
@AcePokeMaster 
today, someone by the name of creator-kami has make me realize that i was wrong,  wrong about a lot of things.

i was a stubborn idiot, it was wrong of me to argue like that,  i could have easily edited the patch myself and there would be no issue.

would you ever forgive me?

http://angsoonli.deviantart.com/journal/I-am-asking-for-forgiveness-519471988

@Nullspeaker @piks @dani87 @pystub @donboricua @kamijoutouma @domzy
it would be wrong of me to just come back and start editing again
i want to earn my place again, not as the BDFL, but as someone who like python and the ch.py

even though i am still a contributor with write access, i am still going to asking for permission cause it would be the right thing to do.

however, i am going offline for a while, i need some time alone after my emotional break down.

**Comment by AcePokeMaster** [comment]
Yes I forgive you. Although I do blame myself as well for pushing you too far as well and for that I am also sorry for.

**Comment by kamijoutouma** [comment]
Sorry for the late reply and I forgive you.
