### ISSUE TITLE
Problem with delete/ban

### ISSUE THREAD

**Issue by ace3df** [Nullspeaker/ch.py#63]
I'm not too sure what's going on here but every time I call to ban a user / delete a message it just doesn't do so.

I call room.delete(message) and room.banUser(user)

Also tried to do both just raw and still no results.

Any idea?

**Comment by Syncro9** [comment]
Use these:
room.delete(user)
room.banUser(message)

I believe it is self explanatory as to why change those to that. If you had even bothered to read the comments in ch.py you would not have ended up asking for help over here.

**Comment by ace3df** [comment]
Ohh I somehow read the post ch.py

don't have to be a dick about it m888
simple mistake on my end

**Comment by piks** [comment]
So thats what they call helping people these days, wow the worlds become pathetic

**Comment by cellsheet** [comment]
@Syncro9 fun fact: if you bothered to read the code in ch.py you would not have ended up using ch.py.

**Comment by geekboyswag** [comment]
LOL people still uses ch.py? -.-

**Comment by cellsheet** [comment]
You would be supprised.

**Comment by Syncro9** [comment]
What makes you assume I use ch,py? I used do that until a few months ago but then I saw the light.

**Comment by cellsheet** [comment]
my appologies

**Comment by Syncro9** [comment]
It's alright, not saying I do not feel the sarcasm in your statement but then again I think everything everyone says is sarcasm.

I simply don't care enough if someone uses ch.py or something even worse. If it works (even though it doesn't really rip) and the people using it are happy then why not.
