### ISSUE TITLE
Unknown Data

### ISSUE THREAD

**Issue by 6317** [Nullspeaker/ch.py#68]
[Printed in console]
unknown data: ['time', '1460136198.55']
unknown data: ['seller_name', 'botnamet', '7725338125882817']
[keeps on repeating]
unknown data: ['']
unknown data: ['']
unknown data: ['']
unknown data: ['']
unknown data: ['']
unknown data: ['']
unknown data: ['']
unknown data: ['']
Also crashes if any user joins or refresh their browser
(C:\Users\i\Desktop\chatango bot 123\New folder\ch.py:1381) onLeave() takes 3 positional arguments but 4 were given

**Comment by asl97** [comment]
"unknown data" is because debugging mode was enable,

as for the onLeave (and possibly onJoin), it's cause the function in your bot is outdated.

**Comment by 6317** [comment]
oh got it thanks
