### ISSUE TITLE
Login as anon

### ISSUE THREAD

**Issue by Uzytkownik2** [Nullspeaker/ch.py#69]
Is it possible to join some room as Anon instead of register user?

**Comment by asl97** [comment]
It is already possible, or at least was if it been broken by updates.

**Comment by Uzytkownik2** [comment]
I think it doesn't work or I'm doing something wrong. Every time when I'm leaving fields **User name** and **User password** blank, then an error occurs (**Invalid argument was supplied** translated from my language).

![error](https://cloud.githubusercontent.com/assets/20256895/17403146/bf53e168-5a56-11e6-903c-5066e33a8bd1.JPG)

**Comment by asl97** [comment]
that is another error: https://github.com/Nullspeaker/ch.py/issues/54
